# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml

include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml


before_script:
  - wget https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64 -O /usr/bin/sops
  - chmod +x /usr/bin/sops
  - sops --decrypt --in-place proxmox-gitlab.tfbackend

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup

fmt:
  extends: .terraform:fmt
  needs: []
  tags:
    - dev

validate:
  extends: .terraform:validate
  needs: []
  tags:
    - dev

build:
  extends: .terraform:build
  tags:
    - staging

deploy:
  extends: .terraform:deploy
  tags:
    - prod
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
  
cleanup:
  extends: .terraform:destroy
  tags:
    - prod
  dependencies:
    - deploy
  environment:
    name: $TF_STATE_NAME
