# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml

include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml


before_script:
  - | 
    SOPSVERSION=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/mozilla/sops.git '*.*.*' | tail --lines=1 | cut --delimiter='/' --fields=3)
    PACKAGEVERSION=$(echo $SOPSVERSION | sed 's/v//')
    curl https://github.com/mozilla/sops/releases/download/${SOPSVERSION}/sops_${PACKAGEVERSION}_amd64.deb -o sops_${PACKAGEVERSION}_amd64.deb
    sudo dpkg -i sops_${PACKAGEVERSION}_amd64.deb
  - sops --decrypt --in-place proxmox.config.tfbackend

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup

fmt:
  extends: .terraform:fmt
  needs: []
  tags:
    - dev

validate:
  extends: .terraform:validate
  needs: []
  tags:
    - dev

build:
  extends: .terraform:build
  tags:
    - staging

deploy:
  extends: .terraform:deploy
  tags:
    - prod
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
